config/routes.rb
Rails.application.routes.draw do
  get 'users/info', to: 'users#info'
  post '/users/charge', to: 'users#charge'
  get '/users/cancel_subscription', to: 'users#cancel_subscription'

  devise_for :users
  root to: "home#index"
  resources :publications, only: [:index, :show]
  namespace :admin do
    resources :publications
  end

end

app/models/publication.rb
class Publication < ActiveRecord::Base
end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :subscription

  after_create :create_subscription
  def create_subscription
    Subscription.create(user_id: id) if subscription.nil?
  end
end

app/controllers/admin/publications_controller.rb
class Admin::PublicationsController < AdminController
  before_filter :find_publication, only: [:show, :edit, :update, :destroy]

  def index
    @publications = Publication.all
  end

  def show
    
  end

  def new
    @publication = Publication.new
  end

  def create
    @publication =
    Publication.new(publication_params)

    if @publication.save
      redirect_to
      admin_publication_path(@publication)
    else
      render :new, alert: "Something went wrong."
    end   
  end

  def edit
    
  end

  def update
    if @publication.update(publication_params)
      redirect_to
      admin_publication_path(@publication)
    else
      render :edit, alert: "Something went wrong."
    end
  end

  def destroy
    @publication.destroy
    redirect_to admin_publications_path, alert:
    "Successfully deleted publication."
  end

  private
  def find_publication
    @publication = Publication.find(params[:id]) 
  end

  def publication_params
    params.require(:publication).permit(:title, :description, :file_url)
  end


end

app/controllers/admin_controller.rb
class AdminController <ApplicationController
  before_filter :check_for_admin
  def check_for_admin
    if current_user.nil? || !current_user.is_admin?
      redirect_to root_path, alert: "You must be an admin to access this path."
    end  
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    
  end

end

app/controllers/publications_controller.rb
class PublicationsController < ApplicationController
  before_filter :check_for_subscription, only: :show
  def index
    @publications = Publication.all
  end

  def show
    @publication = Publication.find(params[:id])
  end

  def check_for_subscription
    unless current_user.subscription.active
      flash[:alert] = "You must be a subscriber to access this content."
      redirect_to publications_path    
    end 
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  skip_before_action :verify_authenticity_token
  def info
    @subscription = current_user.subscription
    if @subscription.active
      @stripe_customer = Stripe::Customer.retrieve(@subscription.stripe_user_id)
      @stripe_subscription = @stripe_customer.subscription.first
    end
  end

  def cancel_subscription
    @stripe_customer = Stripe::Customer.retrieve(@subscription.strip_user_id)
    @stripe_subscription = @stripe_customer.subscriptions.first

    @stripe_subscription.delete
    current_user.subscription.active = false
    current_user.subscription.save
    redirect_to users_info_path
    
  end

  def charge
    token= params["stripeToken"]
    customer = Stripe::Customer.create(
      source: token,
      plan: 'classicsubscription1',
      email: current_user.email
      )

    current_user.subscription.stripe_user_id = customer.id
    current_user.subscription.active = true
    current_user.subscription.save

    redirect_to users_info_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/publications/edit.html.erb
<h3>Edit <%= @publication.title %></h3>

<%= form_for @publication, url:
admin_publication_path(@publicaiton) do |f| %>
  <div class="form-group">
    <label>Title</label>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class="form-group">
    <label>Description</label>
    <%= f.text_area :description, class: 'form-control' %>
  </div>
  <div class="form-group">
    <label>File URL</label><%= f.text_field :file_url, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.submit "Update Publication", class: 'btn btn-primary' %>
  </div>
  <% end %>

app/views/admin/publications/index.html.erb
<h2>Publications</h2>

<div>
<%= link_to "New Publication", new_admin_publication_path, class: 'btn btn-primary' %>
</div>

<% @publications.each do |publication| %>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title"><%= publication.title %></h3>
    </div>
    <div class="panel-body">
      <p><%= publication.description %></p>
      <p><%= publication.file_url %></p>
    </div>
    <div class="panel-footer">
      <%= link_to "View more details", admin_publication_path(publication), class: "btn btn-default" %>
      <%= link_to "Edit", edit_admin_publication_path(publication), class: "btn btn-default" %>
    </div>
  </div>
<% end %>

app/views/admin/publications/new.html.erb
<h3>New Publication</h3>

<%= form_for @publication, url:
admin_publications_path do |f| %>
  <div class="form-group">
    <label>Title</label>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class="form-group">
    <label>Description</label>
    <%= f.text_area :description, class: 'form-control' %>
  </div>
  <div class="form-group">
    <label>File URL</label><%= f.text_field :file_url, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.submit "Update Publication", class: 'btn btn-primary' %>
  </div>
  <% end %>

app/views/admin/publications/show.html.erb
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title"><%= @publication.title %></h3>
    </div>
    <div class="panel-body">
      <p><%= @publication.description %></p>
      <p><%= @publication.file_url %></p>
    </div>
  </div>

app/views/application/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">

      <a class="navbar-brand" href="/">ClassicWine Subscription</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">


      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
        <li>
          <%= link_to current_user.email, users_info_path %>
        </li>

        <li>
          <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
        </li>
        <% else %>
            <li>
              <%= link_to "Sign in", new_user_session_path %>
            </li>
            <li>
              <%= link_to "Sign up", new_user_registration_path %>
            </li>
        <% end %>


      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/home/index.html.erb
<h1>Hello World!</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Classic Wine Subscription</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" 
</head>
<body>
  <%= render 'nav' %>


<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/publications/index.html.erb
<h2>Publications</h2>

<% @publications.each do |publication| %>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title"><%= publication.title %></h3>
    </div>
    <div class="panel-body">
      <p><%= publication.description %></p>
      <p><%= publication.file_url %></p>
    </div>
    <div class="panel-footer">
      <%= link_to "View more details", publication_path(publication), class: "btn btn-default" %>
    </div>
  </div>
<% end %>

app/views/users/_form.html.erb
<h4>Start your subscription now for $ 15 per month.</h4>
<form action=" /users/charge" method="POST" id="payment-form">
  <span class="payment-errors"></span>

  <div class="row">
    <div class="col-md-6">
      <label>Card Number</label>
      <input class="form-control" type="text" size="20" data-stripe="number" placeholder="4242424242424242"/>
    </div>
  </div>
  <br />
  <div class="row">
    <div class="col-xs-2">
      <label>CVC</label>
      <input type="text" data-strip="cvc" class="form-control" placeholder="123">
    </div>
  </div>
  <br />
  <div class="row">
    <div class="col-xs-2">
      <label>Expiration</label>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-1">
      <label>MM</label>
      <input type="text" data-stripe="exp-month" class="form-control" placeholder="01">
    </div>
  </div>
    <div class="row">
    <div class="col-xs-1">
      <label>YYYY</label>
      <input type="text" data-stripe="exp-year" class="form-control" placeholder="2020">
    </div>
  </div>

  <div class="row">
    <br/><button class="btn btn-primary" type="submit">Create Subscription</button>
  </div>
</form>

<script type="text/javascript" src="https://js.stripe.com/v2/"></script>

<script type="text/javascript">
  // This identifies your website in the createToken call below
  Stripe.setPublishableKey('pk_test_0jnysKVtteeH7sqPpfFseL0P');
  // ...

  function stripeResponseHandler(status, response) {
    var $form = $('#payment-form');

    if (response.error) {
      // Show the errors on the form
      $form.find('.payment-errors').text(response.error.message);
      $form.find('button').prop('disabled', false);
    } else {
      // response contains id and card, which contains additional card details
      var token = response.id;
      // Insert the token into the form so it gets submitted to the server
      $form.append($('<input type="hidden" name="stripeToken" />').val(token));
      // and submit
      $form.get(0).submit();
  }
};

  jQuery(function($) {
  $('#payment-form').submit(function(event) {
    var $form = $(this);

    // Disable the submit button to prevent repeated clicks
    $form.find('button').prop('disabled', true);

    Stripe.card.createToken($form, stripeResponseHandler);

    // Prevent the form from submitting with the default action
    return false;
  });
});
</script>

app/views/users/info.html.erb
<div class="container">
  <h3>Account for <%= current_user.email %></h3>
  <% if @subscription.active %>
    <h3>Current plan renews at: <%= Time.at(@stripe.subscription["current_period_end"]).strftime("%D") %></h3>
    <%= link_to "Cancel subscription",
    users_cancel_subscription_path %>
  <% else %>
    <%= render 'form' %>
  <% end %>
</div>